apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nu2uzdin0-go 
  janus-idp.io/tekton: nu2uzdin0-go
  backstage.io/kubernetes-id: nu2uzdin0-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nu2uzdin0-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml