apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nu2uzdin0-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:ed71575d607f0197cfcb60ef4b95393b46f6ce93@sha256:2eb4ddcbaaf4baee82c6cab305b9a9b77ca096ccc9f0d2555391894af1f646ab
          name: container-image
